/*
 * Charlie Harpur
 * 05/04/2018
 * Ideal Weight Calculator
 */

package idealWeightCalculator;

/**
 *
 * @author chhar9972
 */
public class idealWeightCalculator extends javax.swing.JFrame {
    
    /**
     * Creates new form idealWeightCalculator
     */
    public idealWeightCalculator() {
        initComponents();
        //creates a new thread so I can automatically update the ideal weight and continue to have functionality of the rest of the program
        OutputThread output = new OutputThread();
        output.start();
    }
    public class OutputThread extends Thread
    {
        @Override
        public void run()
        {
            double idealWeightMax, idealWeightMin, height;
            String name, system;
            while (true)
            {
                //makes sure a double is entered in the height field
                try
                {
                    height = Double.parseDouble(fieldHeight.getText());
                    //If the selected item in comboSystem is equal to cm it sets the system string to kg otherwise it sets it to lbs
                    system = comboSystem.getSelectedItem() == "Cm" ? "kg" : "lbs";
                    //converts cm to meters for math if the system is metric
                    height /= "kg".equals(system) ? 100 : 1;
                    //Does the different math based on wether the system is metric or imperial
                    idealWeightMax = "kg".equals(system) ? height * height * 25 : height * height * 25 / 703;
                    idealWeightMin = "kg".equals(system) ? height * height * 18.5 : height * height * 18.5 / 703;
                    name = fieldName.getText();
                        labelOutput.setText ("<html>" +
                                name + "'s ideal weight based on their height is " + idealWeightMin + system + " to " + idealWeightMax + system + 
                                "</html>");
                }
                //catches an improper format error
                catch (NumberFormatException nfe)
                {
                    //Tells the user to enter a number
                    labelOutput.setText("<html>"
                            + "Please only enter numeric values into the height field"
                            + "</html>");
                }
            }
            //}
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        comboSystem = new javax.swing.JComboBox();
        labelName = new javax.swing.JLabel();
        labelHeight = new javax.swing.JLabel();
        fieldName = new javax.swing.JTextField();
        fieldHeight = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        labelOutput = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ideal Weight");

        comboSystem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cm", "Inches" }));

        labelName.setText("Name:");

        labelHeight.setText("Height:");

        fieldName.setText("John Doe");

        fieldHeight.setText("150");
        fieldHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldHeightActionPerformed(evt);
            }
        });

        jLabel1.setText("Ideal Weight Calculator");

        labelOutput.setText("OUTPUT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelHeight)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboSystem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelName)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fieldName))
                                .addComponent(jLabel1)))
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName)
                    .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHeight)
                    .addComponent(comboSystem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldHeightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new idealWeightCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox comboSystem;
    private javax.swing.JTextField fieldHeight;
    private javax.swing.JTextField fieldName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelHeight;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelOutput;
    // End of variables declaration//GEN-END:variables
}
